---

- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Install Apache2 Packages 
    apt:  name=apache2 state=present

  - name: Start Apache Service
    service: name=apache2 state=started enabled=true

  - name: Create Dir to Downlaod Tomcat. 
    file: path=/opt/SP/apps/tomcat state=directory

  - name: Install Java 1.8 
    apt: name=default-jdk state=present


  - name: Download Tomcat
    get_url: url=http://apachemirror.wuchna.com/tomcat/tomcat-8/v8.5.51/bin/apache-tomcat-8.5.51.tar.gz dest=/opt/SP/apps/tomcat.tar.gz mode=0755 

  - name: Extract Tomcat
    command: "tar zxf /opt/SP/apps/tomcat.tar.gz  -C /opt/SP/apps/tomcat --strip-components 1"

  - name: Copy Index Page Files
    copy: src=/root/mindtree-devops-30Jan2020/04-Terraform/03-Ansible-Deploy/ansible/04-Tomcat/templates/test.html dest=/opt/SP/apps/tomcat/webapps/ mode=0644
    notify: 
    - Restart Tomcat


  - name: Copy Petclinic Project War Files
    copy: src=/root/.jenkins/workspace/petclinic_artifact/petclinic.war dest=/opt/SP/apps/tomcat/webapps/ mode=0644

  handlers:
  - name: Restart Tomcat
    shell: "nohup sh /opt/SP/apps/tomcat/bin/catalina.sh start" 
